
development:
  adapter: mysql2
  database: web_mashup_development
  pool: 5

test:
  adapter: mysql2
  database: web_mashup_development
  pool: 5

production:
  adapter: mysql2
  database: web_mashup_development
  pool: 5
