
development:
  adapter: mysql2
  database: web_mashup_development
  pool: 5

test: &test
  adapter: mysql2
  database: web_mashup_development
  pool: 5

production:
  adapter: mysql2
  database: web_mashup_development
  pool: 5

cucumber:
  <<: *test
